### ISSUE TITLE
Exception gets thrown for single source chip

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/tweakwcs#134]
Creation of the bounding polygon for input exposures as performed by WCSImageCatalog._calc_chip_bounding_polygon results in an unusable polygon when only 1 source is identified for a chip.  The Exception gets thrown when this bounding_polygon gets used to try to create a WCSGroupCatalog object in the 'update_bounding_polygon()' method (Line 589, wcsimage.py).  The Exception that gets thrown is:

```
ab = SP.multi_union([a1, a4])
Traceback (most recent call last):
  File "C:\Users\Warren\miniconda3\envs\rthstdev\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-2631e866ca12>", line 1, in <module>
    ab = SP.multi_union([a1, a4])
  File "C:\Users\Warren\miniconda3\envs\rthstdev\lib\site-packages\spherical_geometry\polygon.py", line 1165, in multi_union
    return g.union()
  File "C:\Users\Warren\miniconda3\envs\rthstdev\lib\site-packages\spherical_geometry\graph.py", line 407, in union
    self._sanity_check("union - find all intersections")
  File "C:\Users\Warren\miniconda3\envs\rthstdev\lib\site-packages\spherical_geometry\graph.py", line 390, in _sanity_check
    assert len(node._edges) >= 2
AssertionError
```

**Comment by stsci-hack** [comment]
I have a pickle file with polygons for a set of exposures that trigger this Exception which can be used to debug this issue.

**Comment by mcara** [comment]
In the list of polygons (in the pickle), which one corresponds to an image with a single source?
