### ISSUE TITLE
Variable referenced before assignment

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/tweakwcs#55]
I am using tweakwcs (505e21a).  In testing our software, the error below was raised.  

```Traceback (most recent call last):
  File "/Users/mdelapena/repos/hlapipeline/tests/test_bigRandom.py", line 124, in random_align
    datasetTable = alignimages.perform_align([dataset])
  File "/Users/mdelapena/repos/hlapipeline/hlapipeline/alignimages.py", line 301, in perform_align
    fit_rms, fit_num = algorithm_name(imglist, reference_catalog, print_fit_parameters=print_fit_parameters)
  File "/Users/mdelapena/repos/hlapipeline/hlapipeline/alignimages.py", line 443, in match_2dhist_fit
    tweakwcs.tweak_image_wcs(imglist, reference_catalog, match=match)
  File "/Users/mdelapena/miniconda3/envs/astroconda/lib/python3.6/site-packages/tweakwcs-0.2.0.dev1+g505e21a2-py3.6-macosx-10.7-x86_64.egg/tweakwcs/imalign.py", line 490, in tweak_image_wcs
    meta={'orig_image_nddata': img}
  File "/Users/mdelapena/miniconda3/envs/astroconda/lib/python3.6/site-packages/tweakwcs-0.2.0.dev1+g505e21a2-py3.6-macosx-10.7-x86_64.egg/tweakwcs/wcsimage.py", line 98, in __init__
    self.catalog = catalog
  File "/Users/mdelapena/miniconda3/envs/astroconda/lib/python3.6/site-packages/tweakwcs-0.2.0.dev1+g505e21a2-py3.6-macosx-10.7-x86_64.egg/tweakwcs/wcsimage.py", line 194, in catalog
    self.calc_bounding_polygon()
  File "/Users/mdelapena/miniconda3/envs/astroconda/lib/python3.6/site-packages/tweakwcs-0.2.0.dev1+g505e21a2-py3.6-macosx-10.7-x86_64.egg/tweakwcs/wcsimage.py", line 424, in calc_bounding_polygon
    self._calc_cat_convex_hull()
  File "/Users/mdelapena/miniconda3/envs/astroconda/lib/python3.6/site-packages/tweakwcs-0.2.0.dev1+g505e21a2-py3.6-macosx-10.7-x86_64.egg/tweakwcs/wcsimage.py", line 406, in _calc_cat_convex_hull
    ra[-1] = ra[0]
UnboundLocalError: local variable 'ra' referenced before assignment
```

**Comment by mcara** [comment]
Should be fixed via #56.
